source 'https://rubygems.org'

# Ruby microservice vulnerabilities
gem 'internal_ruby_auth', '~> 1.0.0'
gem 'company_api_framework', '2.1.0'
gem 'private_ruby_utils', '>= 1.5.0'
gem 'internal_service_client', '~> 2.0'

# Local path gems to missing workspaces
gem 'internal_ruby_models', path: './missing-ruby-workspace/models'
gem 'company_ruby_tools', path: '../nonexistent-ruby-libs/tools'

group :development, :test do
  gem 'internal_ruby_testing', '~> 0.5.0'
end
